-- ============================================================
-- list-payments-for-duplicate-transactions.sql
--
-- READ-ONLY. Given the pre-fix "duplicate transaction order" list (JSON output
-- of check-duplicate-transaction-order.sql), show a readable before/after for
-- each affected transaction.
--
--   invoice_before = reconstructed from the OLD order in the JSON
--                    (INV-{outlet.sequence_id}.{old order}); the outlet
--                    sequence_id was not changed by the fix.
--   invoice_after  = the current payment.invoice_id (regenerated by the fix).
--
-- Paste the JSON array between the $json$ markers, then run.
--
--   psql "$POSTGRES_CONNECTION_STRING" -f migration/list-payments-for-duplicate-transactions.sql
-- ============================================================

WITH input AS (
  SELECT $json$
  [ PASTE YOUR JSON ARRAY HERE ]
  $json$::jsonb AS data
),
dup AS (
  SELECT (e->>'id')::uuid   AS transaction_id,
         (e->>'order')::int AS old_order
  FROM input, jsonb_array_elements(data) AS e
)
SELECT
  u.name            AS merchant_name,
  u.email           AS merchant_email,
  t.customer_name   AS customer_name,
  -- New-format invoices (INV-<seq>.<order>) were order-derived and regenerated
  -- by the fix, so invoice_before is reconstructed from the old order.
  'INV-' || COALESCE(o.sequence_id::text, '0')
         || '.' || lpad(d.old_order::text, 4, '0')  AS invoice_before,
  p.invoice_id      AS invoice_after,
  t.created_at      AS transaction_created_at,
  t.deleted_at      AS deleted_at
FROM dup d
JOIN      transaction t ON t.id = d.transaction_id
LEFT JOIN users        u ON u.id = t.merchant_id
LEFT JOIN outlets      o ON o.id = t.outlet_id
LEFT JOIN payment      p ON p.transaction_id = t.id
-- Skip old-format invoices (e.g. INV-303006202659, no dot); keep new-format only.
WHERE p.invoice_id LIKE 'INV-%.%'
ORDER BY merchant_name, invoice_before, t.created_at;
