version: 0.0
os: linux

files:
  - source: package.json
    destination: /home/ec2-user/cucibayargo/package.json
    overwrite: true  
  - source: /dist/
    destination: /home/ec2-user/cucibayargo/dist/  
  - source: /scripts/
    destination: /home/ec2-user/cucibayargo/scripts/ 

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
