version: 0.0
os: linux
files:
  - source: /dist/
    destination: /var/www/html/  # Destination folder in the EC2 instance
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
