version: 0.0
os: linux
files:
  - source: /dist/
    destination: /home/ec2-user/cucibayargo/dist/  # Transfer build artifacts to the 'dist' folder
hooks:
  BeforeInstall:
    - location: /home/ec2-user/cucibayargo/scripts/install_dependencies.sh  # Reference script in the 'scripts' folder
      timeout: 300
  ApplicationStart:
    - location: /home/ec2-user/cucibayargo/scripts/start_server.sh  # Reference script in the 'scripts' folder
      timeout: 300
