version: 0.0
os: linux

files:
  - source: dist/
    destination: /home/ec2-user/cucibayargo/dist
  - source: scripts/
    destination: /home/ec2-user/cucibayargo/scripts
  - source: package.json
    destination: /home/ec2-user/cucibayargo
  - source: package-lock.json
    destination: /home/ec2-user/cucibayargo

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
