version: 0.0
os: linux
files:
  - source: /dist/
    destination: /home/ec2-user/cucibayargo/  # Change the destination to a new folder
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
