version: 0.0
os: linux

files:
  - source: package.json
    destination: /home/ec2-user/cucibayargo/
    overwrite: true  
  - source: /dist/
    destination: /home/ec2-user/cucibayargo/dist/  
  - source: /aws/
    destination: /home/ec2-user/cucibayargo/aws/ 

hooks:
  AfterInstall:
    - location: aws/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: aws/scripts/start_server.sh
      timeout: 300
      runas: root
