version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - appspec.yml
    - package-lock.json
    - package.json
    - 'dist/**/*'   
    - 'aws/**/*'   
  discard-paths: no
