/**
 * sync-old-to-v2.ts
 *
 * One-directional incremental data sync: OLD database (v1..v6) -> v2 database.
 *
 * Context
 * -------
 * v2 keeps the same tables & UUID primary keys as the old DB (the user-level
 * migration only ADDED columns/tables). So we can upsert changed rows by id.
 * The old base tables have no updated_at/deleted_at, so change tracking is
 * added by migration/sync/01-old-db-tracking.sql (RUN THAT ONCE FIRST):
 *   - updated_at column + BEFORE INSERT/UPDATE trigger on every synced table
 *   - sync_deletions audit table + AFTER DELETE trigger
 *
 * Each run, per table (in FK-parent-first order):
 *   1. Read the watermark from v2.sync_state.
 *   2. Pull rows from old where updated_at > watermark (minus a small overlap),
 *      keyset-paginated by (updated_at, id).
 *   3. Upsert into v2 on the columns common to BOTH schemas (type-compatible),
 *      via INSERT ... ON CONFLICT (id) DO UPDATE. Idempotent.
 *   4. Advance the watermark.
 * Then apply v2 transforms (create default outlet per new merchant + backfill
 * outlet_id), remap subscriptions to the new plan structure, and replay deletes.
 *
 * The very first run (watermark = epoch) performs the full initial backfill.
 *
 * Env:
 *   OLD_POSTGRES_CONNECTION_STRING   source (old v1..v6 DB)
 *   POSTGRES_CONNECTION_STRING       target (v2 DB) — same var the app uses
 *   SYNC_BATCH_SIZE                  optional, default 500
 *
 * Run:  npm run sync:once      (single pass, then exit)
 *       npm run sync:watch     (loop on a schedule via node-cron)
 */

import { Pool, PoolClient } from "pg";
import * as dotenv from "dotenv";

dotenv.config();

// ------------------------------------------------------------------
// Config
// ------------------------------------------------------------------

const BATCH_SIZE = Number(process.env.SYNC_BATCH_SIZE) || 500;

// Re-scan this far behind the stored watermark each run. Guards against two
// rows sharing the exact same updated_at across the watermark boundary; the
// upsert is idempotent so re-processing is harmless.
const OVERLAP_SECONDS = 2;

const EPOCH = "1970-01-01T00:00:00.000Z";
const ZERO_UUID = "00000000-0000-0000-0000-000000000000";

// Lowest-possible id sentinel for keyset pagination, matching the id column's
// type. Not every table keys on a uuid — e.g. expenses.id is a bigint.
function idSentinel(idType: string | undefined): string | number {
  if (idType === "int2" || idType === "int4" || idType === "int8") return 0;
  if (idType === "uuid") return ZERO_UUID;
  return ""; // text / varchar-like
}

// Never copied: sync artifact (updated_at), or regenerated by v2
// (sequence_id is SERIAL/UNIQUE; "order" is set by a v2 INSERT trigger).
const GLOBAL_EXCLUDE = new Set(["updated_at", "sequence_id", "order"]);

// FK-parent-first order. app_subscriptions is handled specially (plan remap).
const TABLES: string[] = [
  "users",
  "customer",
  "service",
  "duration",
  "service_duration",
  "note",
  "transaction",
  "transaction_item",
  "payment",
  "expenses",
  "discounts",
  "printed_devices",
  "app_subscriptions", // special: plan_id/end_date/duration remap
  "app_transactions",
  "users_signup",
  "user_referral",
];

// ------------------------------------------------------------------
// Small helpers
// ------------------------------------------------------------------

const qi = (name: string) => `"${name.replace(/"/g, '""')}"`;

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`Missing required env var ${name}`);
  return v;
}

/** name -> udt_name for a table's public columns. */
async function getColumns(
  client: PoolClient,
  table: string
): Promise<Map<string, string>> {
  const res = await client.query(
    `SELECT column_name, udt_name
       FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = $1`,
    [table]
  );
  const m = new Map<string, string>();
  for (const r of res.rows) m.set(r.column_name, r.udt_name);
  return m;
}

/** Columns present in BOTH schemas with the same udt type, minus excludes. */
function commonColumns(
  src: Map<string, string>,
  tgt: Map<string, string>,
  extraExclude: Set<string> = new Set()
): string[] {
  const cols: string[] = [];
  for (const [name, udt] of src) {
    if (GLOBAL_EXCLUDE.has(name) || extraExclude.has(name)) continue;
    if (tgt.get(name) === udt) cols.push(name);
  }
  return cols;
}

function buildUpsert(table: string, cols: string[], rowCount: number): string {
  const colList = cols.map(qi).join(", ");
  const tuples: string[] = [];
  let p = 1;
  for (let r = 0; r < rowCount; r++) {
    tuples.push(`(${cols.map(() => `$${p++}`).join(", ")})`);
  }
  const nonId = cols.filter((c) => c !== "id");
  const conflict = nonId.length
    ? `DO UPDATE SET ${nonId.map((c) => `${qi(c)} = EXCLUDED.${qi(c)}`).join(", ")}`
    : "DO NOTHING";
  return `INSERT INTO public.${qi(table)} (${colList}) VALUES ${tuples.join(
    ", "
  )} ON CONFLICT (id) ${conflict}`;
}

// ------------------------------------------------------------------
// Watermark / sync_state (lives in v2)
// ------------------------------------------------------------------

async function ensureSyncState(v2: PoolClient): Promise<void> {
  await v2.query(`
    CREATE TABLE IF NOT EXISTS sync_state (
      table_name      text PRIMARY KEY,
      last_synced_at  timestamptz NOT NULL DEFAULT '1970-01-01T00:00:00Z',
      last_cursor     bigint      NOT NULL DEFAULT 0,
      updated_at      timestamptz NOT NULL DEFAULT now()
    )
  `);
}

async function getWatermark(v2: PoolClient, table: string): Promise<string> {
  const res = await v2.query(
    `SELECT last_synced_at FROM sync_state WHERE table_name = $1`,
    [table]
  );
  return res.rows[0]?.last_synced_at
    ? new Date(res.rows[0].last_synced_at).toISOString()
    : EPOCH;
}

async function setWatermark(
  v2: PoolClient,
  table: string,
  ts: string
): Promise<void> {
  await v2.query(
    `INSERT INTO sync_state (table_name, last_synced_at, updated_at)
       VALUES ($1, $2, now())
     ON CONFLICT (table_name)
       DO UPDATE SET last_synced_at = EXCLUDED.last_synced_at, updated_at = now()`,
    [table, ts]
  );
}

/** Subtract the overlap window from a watermark ISO string. */
function scanStart(watermark: string): string {
  return new Date(
    new Date(watermark).getTime() - OVERLAP_SECONDS * 1000
  ).toISOString();
}

// ------------------------------------------------------------------
// Generic table sync
// ------------------------------------------------------------------

async function syncTable(
  old: PoolClient,
  v2: PoolClient,
  table: string
): Promise<number> {
  const srcCols = await getColumns(old, table);
  const tgtCols = await getColumns(v2, table);
  if (srcCols.size === 0 || tgtCols.size === 0) {
    console.log(`  [${table}] skipped (missing in old or v2)`);
    return 0;
  }
  const cols = commonColumns(srcCols, tgtCols);
  if (!cols.includes("id")) {
    console.log(`  [${table}] skipped (no shared uuid id column)`);
    return 0;
  }
  const selectList = cols.map(qi).join(", ");

  const watermark = await getWatermark(v2, table);
  let lastTs = scanStart(watermark);
  let lastId: string | number = idSentinel(srcCols.get("id"));
  let total = 0;

  // Keyset pagination on (updated_at, id).
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const page = await old.query(
      `SELECT ${selectList}, updated_at AS __ts
         FROM public.${qi(table)}
        WHERE (updated_at, id) > ($1, $2)
        ORDER BY updated_at ASC, id ASC
        LIMIT ${BATCH_SIZE}`,
      [lastTs, lastId]
    );
    if (page.rows.length === 0) break;

    const params: any[] = [];
    for (const row of page.rows) {
      for (const c of cols) params.push(row[c]);
    }
    await v2.query(buildUpsert(table, cols, page.rows.length), params);

    const last = page.rows[page.rows.length - 1];
    lastTs = new Date(last.__ts).toISOString();
    lastId = last.id;
    total += page.rows.length;

    // Persist progress per batch so a crash resumes mid-table.
    await setWatermark(v2, table, lastTs);

    if (page.rows.length < BATCH_SIZE) break;
  }

  // For serial/bigint-keyed tables we copy the id verbatim, which does NOT
  // advance v2's owning sequence. Bump it past max(id) so any native v2 insert
  // can't later collide with a synced id. No-op for uuid keys / non-serial ids.
  const idType = srcCols.get("id");
  if (total && (idType === "int2" || idType === "int4" || idType === "int8")) {
    await v2.query(
      `SELECT setval(s.seq, GREATEST(s.mx, 1))
         FROM (
           SELECT pg_get_serial_sequence($1, 'id') AS seq,
                  (SELECT COALESCE(MAX(id), 0) FROM public.${qi(table)}) AS mx
         ) s
        WHERE s.seq IS NOT NULL`,
      [`public.${table}`]
    );
  }

  if (total) console.log(`  [${table}] upserted ${total}`);
  return total;
}

// ------------------------------------------------------------------
// Special: app_subscriptions (remap old plans -> v2 plan structure)
//
// Old plan codes 1bulan/3bulan/6bulan/12bulan -> v2 'basic'; 'gratis' -> v2
// 'gratis'. The old plan rows were DELETED from v2 by the migration, so a raw
// copy of plan_id would dangle. end_date and duration(jsonb) are recomputed to
// match the migration's v15 logic.
// ------------------------------------------------------------------

const PLAN_DAYS: Record<string, number> = {
  "1bulan": 30,
  "3bulan": 90,
  "6bulan": 180,
  "12bulan": 360,
  gratis: 14,
};

function planDays(code: string | null): number {
  if (code && code in PLAN_DAYS) return PLAN_DAYS[code];
  return 30; // matches v15 ELSE 30
}

async function getV2PlanId(v2: PoolClient, code: string): Promise<string> {
  const res = await v2.query(
    `SELECT id FROM app_plans WHERE code = $1 ORDER BY created_at DESC LIMIT 1`,
    [code]
  );
  if (!res.rows[0]) throw new Error(`v2 app_plans missing code '${code}'`);
  return res.rows[0].id;
}

async function syncSubscriptions(
  old: PoolClient,
  v2: PoolClient
): Promise<number> {
  const table = "app_subscriptions";
  const basicId = await getV2PlanId(v2, "basic");
  const gratisId = await getV2PlanId(v2, "gratis");

  // Only include target columns that actually exist in v2.
  const tgt = await getColumns(v2, table);
  const desired = [
    "id",
    "user_id",
    "plan_id",
    "start_date",
    "end_date",
    "status",
    "user_plan_price",
    "duration",
    "created_at",
  ].filter((c) => tgt.has(c));

  const watermark = await getWatermark(v2, table);
  let lastTs = scanStart(watermark);
  let lastId = ZERO_UUID;
  let total = 0;

  // eslint-disable-next-line no-constant-condition
  while (true) {
    const page = await old.query(
      `SELECT s.*, p.code AS __plan_code, s.updated_at AS __ts
         FROM public.app_subscriptions s
         LEFT JOIN public.app_plans p ON p.id = s.plan_id
        WHERE (s.updated_at, s.id) > ($1, $2)
        ORDER BY s.updated_at ASC, s.id ASC
        LIMIT ${BATCH_SIZE}`,
      [lastTs, lastId]
    );
    if (page.rows.length === 0) break;

    const tuples: string[] = [];
    const params: any[] = [];
    let p = 1;
    for (const row of page.rows) {
      const code: string | null = row.__plan_code;
      const days = planDays(code);
      const isGratis = code === "gratis";
      const start: Date | null = row.start_date;
      const endDate = start
        ? new Date(start.getTime() + days * 86400000)
        : null;
      const durationJson = JSON.stringify({
        days,
        original_plan_code: code,
      });

      const valueFor: Record<string, any> = {
        id: row.id,
        user_id: row.user_id,
        plan_id: isGratis ? gratisId : basicId,
        start_date: row.start_date,
        end_date: endDate,
        status: row.status,
        user_plan_price: row.user_plan_price,
        duration: durationJson,
        created_at: row.created_at,
      };

      const ph = desired.map((c) => {
        const placeholder = c === "duration" ? `$${p}::jsonb` : `$${p}`;
        p++;
        params.push(valueFor[c]);
        return placeholder;
      });
      tuples.push(`(${ph.join(", ")})`);
    }

    const nonId = desired.filter((c) => c !== "id");
    const sql = `INSERT INTO public.${qi(table)} (${desired
      .map(qi)
      .join(", ")}) VALUES ${tuples.join(", ")}
      ON CONFLICT (id) DO UPDATE SET ${nonId
        .map((c) => `${qi(c)} = EXCLUDED.${qi(c)}`)
        .join(", ")}`;
    await v2.query(sql, params);

    const last = page.rows[page.rows.length - 1];
    lastTs = new Date(last.__ts).toISOString();
    lastId = last.id;
    total += page.rows.length;
    await setWatermark(v2, table, lastTs);

    if (page.rows.length < BATCH_SIZE) break;
  }

  if (total) console.log(`  [${table}] upserted ${total} (plan-remapped)`);
  return total;
}

// ------------------------------------------------------------------
// Transform: default outlet per merchant + backfill outlet_id
// (idempotent — only touches rows still missing an outlet_id)
// ------------------------------------------------------------------

async function applyOutletBackfill(v2: PoolClient): Promise<void> {
  // v2 users dropped address/phone_number (v13), so seed those as NULL.
  await v2.query(`
    INSERT INTO outlets (merchant_id, code, name, address, phone_number)
    SELECT u.id, 'OTL-001', COALESCE(NULLIF(u.name, ''), 'Outlet Utama'), NULL, NULL
      FROM users u
     WHERE NOT EXISTS (SELECT 1 FROM outlets o WHERE o.merchant_id = u.id)
  `);

  // Each merchant's primary (earliest, active) outlet.
  const primaryOutlet = `
    SELECT DISTINCT ON (merchant_id) merchant_id, id
      FROM outlets
     WHERE deleted_at IS NULL
     ORDER BY merchant_id, sequence_id ASC
  `;

  for (const t of ["customer", "duration", "note", "service", "transaction", "expenses", "discounts"]) {
    await v2.query(`
      UPDATE ${qi(t)} x
         SET outlet_id = o.id
        FROM (${primaryOutlet}) o
       WHERE o.merchant_id = x.merchant_id
         AND x.outlet_id IS NULL
    `);
  }

  // payment inherits its transaction's outlet.
  await v2.query(`
    UPDATE payment p
       SET outlet_id = t.outlet_id
      FROM transaction t
     WHERE p.transaction_id = t.id
       AND p.outlet_id IS NULL
       AND t.outlet_id IS NOT NULL
  `);

  // printed_devices keyed by user_id.
  await v2.query(`
    UPDATE printed_devices pd
       SET outlet_id = o.id
      FROM (${primaryOutlet}) o
     WHERE o.merchant_id = pd.user_id
       AND pd.outlet_id IS NULL
  `);
}

// ------------------------------------------------------------------
// Replay hard deletes recorded on the old DB
// ------------------------------------------------------------------

async function processDeletions(old: PoolClient, v2: PoolClient): Promise<number> {
  const CURSOR_KEY = "__deletions__";
  const cur = await v2.query(
    `SELECT last_cursor FROM sync_state WHERE table_name = $1`,
    [CURSOR_KEY]
  );
  let lastCursor: number = cur.rows[0]?.last_cursor ?? 0;
  const syncable = new Set(TABLES);
  let total = 0;

  // eslint-disable-next-line no-constant-condition
  while (true) {
    const page = await old.query(
      `SELECT id, table_name, row_id
         FROM sync_deletions
        WHERE id > $1
        ORDER BY id ASC
        LIMIT ${BATCH_SIZE}`,
      [lastCursor]
    );
    if (page.rows.length === 0) break;

    for (const row of page.rows) {
      if (syncable.has(row.table_name)) {
        // row_id is text; cast the column so uuid and bigint ids both match.
        await v2.query(
          `DELETE FROM public.${qi(row.table_name)} WHERE id::text = $1`,
          [row.row_id]
        );
        total++;
      }
      lastCursor = Number(row.id);
    }

    await v2.query(
      `INSERT INTO sync_state (table_name, last_cursor, updated_at)
         VALUES ($1, $2, now())
       ON CONFLICT (table_name)
         DO UPDATE SET last_cursor = EXCLUDED.last_cursor, updated_at = now()`,
      [CURSOR_KEY, lastCursor]
    );

    if (page.rows.length < BATCH_SIZE) break;
  }

  if (total) console.log(`  [deletions] applied ${total}`);
  return total;
}

// ------------------------------------------------------------------
// Orchestration
// ------------------------------------------------------------------

export interface SyncSummary {
  skipped: boolean;
  reason?: string;
  durationMs: number;
  tables: Record<string, number>;
  deletions: number;
}

// Session-level advisory lock so two triggers (e.g. overlapping Cloud Run
// instances) can never run the sync concurrently against the same v2 DB.
const ADVISORY_LOCK_KEY = 1398362179; // 0x53594e43 = "SYNC"

export async function runSyncOnce(): Promise<SyncSummary> {
  const oldPool = new Pool({
    connectionString: requireEnv("OLD_POSTGRES_CONNECTION_STRING"),
  });
  const v2Pool = new Pool({
    connectionString: requireEnv("POSTGRES_CONNECTION_STRING"),
  });

  const old = await oldPool.connect();
  const v2 = await v2Pool.connect();
  const started = Date.now();
  const tables: Record<string, number> = {};
  let deletions = 0;
  let locked = false;
  try {
    const lock = await v2.query(
      `SELECT pg_try_advisory_lock($1) AS ok`,
      [ADVISORY_LOCK_KEY]
    );
    if (!lock.rows[0]?.ok) {
      console.log("[sync] another run holds the lock, skipping");
      return {
        skipped: true,
        reason: "locked",
        durationMs: Date.now() - started,
        tables,
        deletions,
      };
    }
    locked = true;

    console.log(`[sync] start ${new Date(started).toISOString()}`);
    await ensureSyncState(v2);

    for (const table of TABLES) {
      tables[table] =
        table === "app_subscriptions"
          ? await syncSubscriptions(old, v2)
          : await syncTable(old, v2, table);
    }

    await applyOutletBackfill(v2);
    deletions = await processDeletions(old, v2);

    const durationMs = Date.now() - started;
    console.log(`[sync] done in ${(durationMs / 1000).toFixed(1)}s`);
    return { skipped: false, durationMs, tables, deletions };
  } finally {
    if (locked) {
      await v2.query(`SELECT pg_advisory_unlock($1)`, [ADVISORY_LOCK_KEY]);
    }
    old.release();
    v2.release();
    await oldPool.end();
    await v2Pool.end();
  }
}

// Run directly: `ts-node src/scripts/sync-old-to-v2.ts`
if (require.main === module) {
  runSyncOnce()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error("[sync] FAILED", err);
      process.exit(1);
    });
}
