name: Deploy to EC2

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ${{ secrets.APP_PATH }} &&
            git fetch &&
            git checkout ${{ github.ref_name }} &&
            git pull origin ${{ github.ref_name }} &&
            export NODE_ENV=${{ github.ref_name == 'staging' ? 'staging' : 'production' }} &&
            npm install &&
            npm run build &&
            pm2 start dist/app.js --name app-${{ github.ref_name }} --update-env
          "
