name: Build and Deploy to CodeDeploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install -g typescript
        npm install

    # Step 4: Build the project
    - name: Build the project
      run: npm run build

    # Step 5: Prepare artifact for deployment
    - name: Prepare artifact
      run: |
        mkdir -p deploy
        cp -R appspec.yml package*.json dist aws deploy/
        cd deploy
        zip -r deploy.zip .

    # Step 6: Upload artifact to S3
    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Upload deployment package
      run: |
        aws s3 cp deploy/deploy.zip s3://cucibayargo-deploy/deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    # Step 2: Deploy using AWS CLI
    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name merchant-api \
          --deployment-group-name production \
          --s3-location bucket=cucibayargo-deploy,bundleType=zip,key=deploy.zip